pipeline {
  agent any
  
  stages {
    stage('Test') {
      steps {
        sh 'echo "Hello"'
      }
    }
  }
   post {
        success {
           sh ' echo "✅ Build and deployment succeeded!"'
        }
        failure {
           sh ' echo "❌ Build or deployment failed."'
        }
   }
}
