pipeline {
  agent any
  
  stages {
    stage('Test') {
      steps {
        sh 'echo "Hello"'
      }
    }
  }
   post {
        success {
            echo '✅ Build and deployment succeeded!'
        }
        failure {
            echo '❌ Build or deployment failed.'
        }
}
